name: Update Universe

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * mon'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update universe
      run: go run .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      if: github.event_name != 'push'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update universe
