name: Update universe

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * mon"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Update universe
      run: go run .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      if: github.event_name != 'push'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update universe
