name: Update universe

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!endsWith(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Configure cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Update universe
      run: go run .
      
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: Update universe
